- name: install elasticsearch
  hosts: tag_Name_elasticsearch
  remote_user: ubuntu
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  
  roles:
    - elasticsearch 
    - kibana
    - nginx
    - logstash
     
